### ISSUE TITLE
Sharing Game success

### ISSUE THREAD

**Issue by IgbozeIsrael** [alpha-fi/cheddar-ecosystem#1]
Can we add a function where users share the results of the games they play on X? The link will embed the following 
1. A photo of their score/or a banner design for the game
2. An invite link to the game site. This could mean users are rewarded when a certain number of invitees play the game
3. Some cheese (555) for new users to claim and begin the game
4. A nada bot verification link can be included too.

**Comment by Megha-Dev-19** [comment]
Resolved #28
