### ISSUE TITLE
Fix Need 555 Cheddar links should two

### ISSUE THREAD

**Issue by Megha-Dev-19** [alpha-fi/cheddar-ecosystem#13]
![Image](https://github.com/alpha-fi/cheddar-ecosystem/assets/9367253/adc31e1d-43a7-4066-b09f-326812d89721)

Ref:
https://app.ref.finance/#a0b86991c6218b36c1d19d4a2e9eb0ce3606eb48.factory.bridge.near|token.cheddar.near

Nadabot:
https://app.nada.bot/

**Comment by htafolla** [comment]
Underline 555 🧀 and Verified Human so they show as links.
