### ISSUE TITLE
Move Cheddar Total Supply to left of Login/Logout

### ISSUE THREAD

**Issue by Megha-Dev-19** [alpha-fi/cheddar-ecosystem#14]

**Comment by Megha-Dev-19** [comment]
@htafolla does this work?


![Image](https://github.com/alpha-fi/cheddar-ecosystem/assets/100185149/d6761849-cdf5-4596-904b-972efbe8d32e)

**Comment by htafolla** [comment]
Yes. Make the color of the text white. Make the cheddar logo bigger.
