### ISSUE TITLE
Add proper Hover and Click Highlights/Shadows to all Buttons

### ISSUE THREAD

**Issue by Megha-Dev-19** [alpha-fi/cheddar-ecosystem#16]

**Comment by Megha-Dev-19** [comment]
@htafolla is there an example which you have in mind? because currently the buttons do have a hover effect, do you want to have shadows?


https://github.com/alpha-fi/cheddar-ecosystem/assets/100185149/fa5e2db4-8a85-4bba-9482-0f47f0053bf8

**Comment by htafolla** [comment]
https://alpha-fi.github.io/cheddar-ui-v1/

**Comment by Megha-Dev-19** [comment]
[Added](https://github.com/alpha-fi/cheddar-ecosystem/commit/818fea531e14fc3cc67f36e8af8c81b6b2c10aaa)
