### ISSUE TITLE
Move ScoreBoard Button next to PowerUp show Trophy 🏆 icon for button

### ISSUE THREAD

**Issue by Megha-Dev-19** [alpha-fi/cheddar-ecosystem#7]

**Comment by Megha-Dev-19** [comment]
@htafolla this is the current design, do you still want me to move the scoreboard next to PowerUp ? 
![Image](https://github.com/alpha-fi/cheddar-ecosystem/assets/100185149/31f344a9-7d94-4218-b2a0-12f912c41703)

**Comment by htafolla** [comment]
Yes and make a button with only the Trophy icon.
