### ISSUE TITLE
Board color does not randomly change on game restart

### ISSUE THREAD

**Issue by Megha-Dev-19** [alpha-fi/cheddar-ecosystem#8]

**Comment by Megha-Dev-19** [comment]
@htafolla I tried refreshing multiple times and it changes the board color, is there a specific case when it doesn't work?
https://drive.google.com/file/d/1kLcMLIwG2sLYua93kgkwZ2hY4zmZUs_v/view?usp=sharing

**Comment by htafolla** [comment]
@Megha-Dev-19 This issue is upon game "Restart."
