### ISSUE TITLE
Update Win/Loss Popup to include cheddar

### ISSUE THREAD

**Issue by Megha-Dev-19** [alpha-fi/cheddar-ecosystem#9]
Show how much Cheddar was Won or Lost per Game on the popup.

![Image](https://github.com/alpha-fi/cheddar-ecosystem/assets/9367253/16fac20a-a6d6-4fcc-8cea-32f431d97c84)

**Comment by Megha-Dev-19** [comment]
@htafolla we already have this, does this work?

![Image](https://github.com/alpha-fi/cheddar-ecosystem/assets/100185149/1e966ed3-616f-4ea1-8826-e9ff9ca5b3e4)

**Comment by htafolla** [comment]
I meant when they Lose show how much Cheddar was lost.

Updated the winning message to be: You farmed X 🧀
